export const CANADA_CITIES = [
  "Abbotsford",
  "Aldergrove",
  "Cornwall",
  "Coutts",
  "Edmundston",
  "Emerson",
  "Fort Frances",
  "Jackman",
  "Johnstown",
  "Lacolle",
  "Lansdowne",
  "Niagara Falls",
  "Saint-Armand",
  "Sarnia",
  "Sault Ste. Marie",
  "St. Stephen",
  "Stanhope",
  "Stanstead",
  "Surrey",
  "Windsor",
  "Woodstock",
] as const;
